apply plugin: 'com.android.application'

android {
    namespace 'com.rama.mako_forever'
    compileSdk 36
    ndkVersion '27.0.12077973'

    defaultConfig {
        applicationId 'com.rama.mako_forever'

        versionCode 1
        versionName '1.0'
    }

    externalNativeBuild {
        cmake {
            path 'CMakeLists.txt'
        }
    }
}